Add information in readme about discontinuation of the project
pmem/knowledge-base pull request #1
Opened 2023-02-10 14:49 UTC by szadam

Preview: https://github.com/szadam/knowledge-base/blob/master/README.md

2023-03-02 15:37 UTC, lukaszstolarczuk requested changes

2023-03-02 15:37 UTC, lukaszstolarczuk commented on README.md
> +The **pmemfile** project will no longer be maintained by Intel.
ha, nope

2023-03-03 11:20 UTC, szadam commented on README.md
> +The **pmemfile** project will no longer be maintained by Intel.
;) done

2023-03-03 12:37 UTC, lukaszstolarczuk approved these changes

2023-03-22 10:21 UTC, merged